In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/Market_Basket_Optimisation.csv",header=None)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,7501,5747,4389,3345,2529,1864,1369,981,654,395,256,154,87,47,25,8,4,4,3,1
unique,115,117,115,114,110,106,102,98,88,80,66,50,43,28,19,8,3,3,3,1
top,mineral water,mineral water,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea,green tea,low fat yogurt,green tea,green tea,green tea,magazines,salmon,frozen smoothie,protein bar,spinach,olive oil
freq,577,484,375,201,153,107,96,67,57,31,22,15,8,4,3,1,2,2,1,1

In [ ]:
df.shape

(7501, 20)

In [ ]:
!pip install pyECLAT

import pandas as pd
from pyECLAT import ECLAT

eclat = ECLAT(data=df)

indices, support = eclat.fit(
    min_support=0.03,
    min_combination=2,
    max_combination=2
)

result = pd.DataFrame(
    support.items(),
    columns=['Itemset', 'Support']
)

print(result.sort_values(by='Support', ascending=False))

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2
Combination 2 by 2

630it [00:12, 50.17it/s]

                              Itemset   Support
4           spaghetti & mineral water  0.059725
8           chocolate & mineral water  0.052660
12               eggs & mineral water  0.050927
16               milk & mineral water  0.047994
13        ground beef & mineral water  0.040928
0               spaghetti & chocolate  0.039195
2             spaghetti & ground beef  0.039195
1                    spaghetti & eggs  0.036528
10                eggs & french fries  0.036395
14  frozen vegetables & mineral water  0.035729
3                    spaghetti & milk  0.035462
6            chocolate & french fries  0.034395
9            pancakes & mineral water  0.033729
15       french fries & mineral water  0.033729
5                    chocolate & eggs  0.033196
7                    chocolate & milk  0.032129
17          mineral water & green tea  0.031063
11                        eggs & milk  0.030796

In [ ]:
from pyECLAT import ECLAT
import pandas as pd

eclat = ECLAT(df)

indices, support = eclat.fit(min_support=0.03,
                       min_combination=2,
                       max_combination=2)

for itemset, sup_ab in support.items():

    A, B = itemset.split('&')

    sup_a = (df == A.strip()).any(axis=1).mean()
    sup_b = (df == B.strip()).any(axis=1).mean()

    confidence = sup_ab / sup_a
    lift = confidence / sup_b

    print("Itemset:", itemset)
    print("Support:", round(sup_ab, 4))
    print("Confidence:", round(confidence, 4))
    print("Lift:", round(lift, 4))
    print("-" * 30)

Combination 2 by 2

630it [00:12, 49.64it/s]

Itemset: spaghetti & chocolate
Support: 0.0392
Confidence: 0.2251
Lift: 1.374
------------------------------
Itemset: spaghetti & eggs
Support: 0.0365
Confidence: 0.2098
Lift: 1.1674
------------------------------
Itemset: spaghetti & ground beef
Support: 0.0392
Confidence: 0.2251
Lift: 2.2912
------------------------------
Itemset: spaghetti & milk
Support: 0.0355
Confidence: 0.2037
Lift: 1.5718
------------------------------
Itemset: spaghetti & mineral water
Support: 0.0597
Confidence: 0.343
Lift: 1.4391
------------------------------
Itemset: chocolate & eggs
Support: 0.0332
Confidence: 0.2026
Lift: 1.1274
------------------------------
Itemset: chocolate & french fries
Support: 0.0344
Confidence: 0.2099
Lift: 1.2283
------------------------------
Itemset: chocolate & milk
Support: 0.0321
Confidence: 0.1961
Lift: 1.5133
------------------------------
Itemset: chocolate & mineral water
Support: 0.0527
Confidence: 0.3214
Lift: 1.3483
------------------------------
Itemset: pancakes & mineral water
Support: 0.0337
Confidence: 0.3548
Lift: 1.4886
------------------------------
Itemset: eggs & french fries
Support: 0.0364
Confidence: 0.2025
Lift: 1.185
------------------------------
Itemset: eggs & milk
Support: 0.0308
Confidence: 0.1714
Lift: 1.3224
------------------------------
Itemset: eggs & mineral water
Support: 0.0509
Confidence: 0.2834
Lift: 1.1888
------------------------------
Itemset: ground beef & mineral water
Support: 0.0409
Confidence: 0.4166
Lift: 1.7475
------------------------------
Itemset: frozen vegetables & mineral water
Support: 0.0357
Confidence: 0.3748
Lift: 1.5725
------------------------------
Itemset: french fries & mineral water
Support: 0.0337
Confidence: 0.1973
Lift: 0.8279
------------------------------
Itemset: milk & mineral water
Support: 0.048
Confidence: 0.3704
Lift: 1.5538
------------------------------
Itemset: mineral water & green tea
Support: 0.0311
Confidence: 0.1303
Lift: 0.9864
------------------------------

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

# Load dataset
df = pd.read_csv('/content/Market_Basket_Optimisation.csv', header=None)

# Convert dataframe into transaction list
transactions = []

for i in range(len(df)):
    transactions.append(
        [str(item) for item in df.iloc[i].dropna().values]
    )

# Transaction Encoding
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df_encoded = pd.DataFrame(te_array, columns=te.columns_)

# Apply FP-Growth
frequent_itemsets = fpgrowth(
    df_encoded,
    min_support=0.03,
    use_colnames=True
)

print("Frequent Itemsets:")
print(frequent_itemsets)

# Generate Association Rules
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.2
)

# Display required columns
result = rules[['antecedents',
                'consequents',
                'support',
                'confidence',
                'lift']]

print("\nAssociation Rules:")
print(result)

Frequent Itemsets:
     support                            itemsets
0   0.238368                     (mineral water)
1   0.132116                         (green tea)
2   0.076523                    (low fat yogurt)
3   0.071457                            (shrimp)
4   0.065858                         (olive oil)
5   0.063325                   (frozen smoothie)
6   0.047460                             (honey)
7   0.042528                            (salmon)
8   0.033329                           (avocado)
9   0.031862                    (cottage cheese)
10  0.030396                      (tomato juice)
11  0.179709                              (eggs)
12  0.087188                           (burgers)
13  0.062525                            (turkey)
14  0.129583                              (milk)
15  0.058526                  (whole wheat rice)
16  0.170911                      (french fries)
17  0.050527                              (soup)
18  0.174110                         (spaghetti)
19  0.095321                 (frozen vegetables)
20  0.080389                           (cookies)
21  0.051060                       (cooking oil)
22  0.046794                         (champagne)
23  0.163845                         (chocolate)
24  0.059992                           (chicken)
25  0.068391                          (tomatoes)
26  0.095054                          (pancakes)
27  0.052393                     (grated cheese)
28  0.043061                       (fresh bread)
29  0.098254                       (ground beef)
30  0.079323                          (escalope)
31  0.049460                     (herb & pepper)
32  0.081056                              (cake)
33  0.032396                          (hot dogs)
34  0.033729                          (brownies)
35  0.030129                            (butter)
36  0.031063          (green tea, mineral water)
37  0.050927               (eggs, mineral water)
38  0.047994               (milk, mineral water)
39  0.035462                   (spaghetti, milk)
40  0.032129                   (milk, chocolate)
41  0.030796                        (milk, eggs)
42  0.036395                (eggs, french fries)
43  0.033729       (french fries, mineral water)
44  0.059725          (spaghetti, mineral water)
45  0.036528                   (spaghetti, eggs)
46  0.035729  (frozen vegetables, mineral water)
47  0.033196                   (eggs, chocolate)
48  0.052660          (chocolate, mineral water)
49  0.034395           (french fries, chocolate)
50  0.039195              (spaghetti, chocolate)
51  0.033729           (pancakes, mineral water)
52  0.040928        (ground beef, mineral water)
53  0.039195            (spaghetti, ground beef)

Association Rules:
            antecedents      consequents   support  confidence      lift
0           (green tea)  (mineral water)  0.031063    0.235116  0.986357
1                (eggs)  (mineral water)  0.050927    0.283383  1.188845
2       (mineral water)           (eggs)  0.050927    0.213647  1.188845
3                (milk)  (mineral water)  0.047994    0.370370  1.553774
4       (mineral water)           (milk)  0.047994    0.201342  1.553774
5           (spaghetti)           (milk)  0.035462    0.203675  1.571779
6                (milk)      (spaghetti)  0.035462    0.273663  1.571779
7                (milk)      (chocolate)  0.032129    0.247942  1.513276
8                (milk)           (eggs)  0.030796    0.237654  1.322437
9                (eggs)   (french fries)  0.036395    0.202522  1.184961
10       (french fries)           (eggs)  0.036395    0.212949  1.184961
11          (spaghetti)  (mineral water)  0.059725    0.343032  1.439085
12      (mineral water)      (spaghetti)  0.059725    0.250559  1.439085
13          (spaghetti)           (eggs)  0.036528    0.209801  1.167446
14               (eggs)      (spaghetti)  0.036528    0.203264  1.167446
15  (frozen vegetables)  (mineral water)  0.035729    0.374825  1.572463
16          (chocolate)           (eggs)  0.033196    0.202604  1.127397
17          (chocolate)  (mineral water)  0.052660    0.321400  1.348332
18      (mineral water)      (chocolate)  0.052660    0.220917  1.348332
19       (french fries)      (chocolate)  0.034395    0.201248  1.228284
20          (chocolate)   (french fries)  0.034395    0.209927  1.228284
21          (spaghetti)      (chocolate)  0.039195    0.225115  1.373952
22          (chocolate)      (spaghetti)  0.039195    0.239219  1.373952
23           (pancakes)  (mineral water)  0.033729    0.354839  1.488616
24        (ground beef)  (mineral water)  0.040928    0.416554  1.747522
25          (spaghetti)    (ground beef)  0.039195    0.225115  2.291162
26        (ground beef)      (spaghetti)  0.039195    0.398915  2.291162

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)